### ISSUE TITLE
add instructions for AWS access key

### ISSUE THREAD

**Issue by samsammurphy** [mapbox/rio-tiler#18]
HI Vincent,

Thanks again for your awesome medium [article](https://blog.mapbox.com/combining-the-power-of-aws-lambda-and-rasterio-8ffd3648c348). It has inspired me to check out AWS. The first link in that article sent me here. Following the example to get a Landsat tile

```
>>> from rio_tiler import landsat8
>>> tile = landsat8.tile('LC08_L1TP_016037_20170813_20170814_01_RT', 71, 102, 8)
```

Looks like I need to set my AWS access key.

```
AttributeError: 'NoneType' object has no attribute 'access_key'
```
I'm a complete newb at AWS so don't know how to do that. Could you provide instructions in the README.md?

(if I find out I'll make a PR)

Thanks! ^_^

**Comment by vincentsarago** [comment]
Hi @samsammurphy, 
Thanks for opening the issue.

please refer to http://boto3.readthedocs.io/en/latest/guide/configuration.html docs as explained in https://mapbox.github.io/rasterio/topics/vsi.html?highlight=aws 
basically you need either: 
- Shared credential file (~/.aws/credentials)
- AWS config file (~/.aws/config)

let me know if it fixes it

**Comment by samsammurphy** [comment]
Hi @vincentsarago,

Thanks, that fixed my credentials.
