### ISSUE TITLE
CURL error

### ISSUE THREAD

**Issue by samsammurphy** [mapbox/rio-tiler#19]
Hey Vincent,

I hit a CURL error (already fixed) but thought I should mention it here. This is for Linux Mint 18.1 Serena.

This worked
```
>>> from rio_tiler import landsat8
>>> bounds = landsat8.bounds('LC08_L1TP_016037_20170813_20170814_01_RT')
# {'sceneid': 'LC08_L1TP_016037_20170813_20170814_01_RT', 'bounds': [-81.30836, 32.10539, -78.82045, 34.22818]}
```

However getting metadata and tile both required curl (it seems), I hit this error:
```
rasterio._err.CPLE_HttpResponseError: CURL error: error setting certificate verify locations:   CAfile: /etc/pki/tls/certs/ca-bundle.crt   CApath: none
```
I made sure that I had the `ca-certificates` package

`apt-get install ca-certificates`

(the latest version was already installed). Then I fixed the CURL certificates path in .bashrc

`export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt`

Everything now seems to work fine =D !

It was a bit weird (for me) that curl was looking in the wrong place (i.e. `/etc/pki/tls/certs/ca-bundle.crt`), not sure how to proceed (e.g. note in docs, fix in code, ignore)?

**Comment by vincentsarago** [comment]
Gonna close this issue because it's not related to `rio-tiler` itself.
