### ISSUE TITLE
Option to apply vrt colormap to png

### ISSUE THREAD

**Issue by kriscarle** [mapbox/rio-tiler#4]
There is an example of how to convert it and apply it via pillow [here](https://github.com/mmcfarland/foss4g-lambda-demo/blob/master/geop/geo_utils.py#L173). Happy to submit a PR if there is a generic approach that works. 

Looks like one way to do it is make it an option on `array_to_img` and then return the vrt source from `tile_band_worker` and then `aws.tile`. Then add a `color_table_to_palette` helper function to utils. That way users that want to use the vrt color table can extract it and pass it to `array_to_img`?

I guess another option is to use rasterio's `write_colormap` but it looks like that would require writing the data out to vsimem and reading it back? Would that be better than applying it to the PNG directly?

(Also thanks for this repo :) I was struggling to get my own WarpedVRT code to work, then I found this)

**Comment by vincentsarago** [comment]
👋 Hi @kriscarle, thanks for opening this issue. 

So to keep everything as simple as possible we could:
- add an option in `array_to_img` to apply a palette to a 1 band image ([example](https://github.com/RemotePixel/remotepixel-py/blob/b2f590efc48d1a715c79c44b1906910ce2f2a107/remotepixel/l8_ovr.py#L92-L94)). 
- add a `utils.get_palette` function that accept either a rasterio dataset (as in `geop`) or a `color_palette` name (local palettes shipped within rio-tiler) 

btw, there are some work to do to fully support one band output image (e.g. add mask) : https://github.com/mapbox/rio-tiler/blob/f33930f4da0493c6941e5c3e617364eb9caca86a/rio_tiler/utils.py#L354-L355

**Comment by kriscarle** [comment]
Hi @vincentsarago I was able to get it working like this, using rasterio's built in support for writing colormaps and MemoryFile. The PIL palette doesn't support RGBA values, plus I think this example can easily be adapted to support multiple bands.

```python
import rasterio
from rio_tiler import aws
from rasterio.io import MemoryFile

def tile(event, context):
    args = event['pathParameters']
    x = int(args['x'])
    y = int(args['y'])
    z = int(args['z'])

    bucket = 'my-bucket'
    key = 'data.vrt'
    tile = aws.tile(bucket, key, x, y, z, 1, 256)
    with rasterio.open('s3://{}/{}'.format(bucket, key)) as src:
      colormap = src.colormap(1)
      meta = src.meta
      meta['driver'] = 'PNG'
      meta['height'] = 256
      meta['width'] = 256
  
      with MemoryFile() as memfile:
        with memfile.open(**meta) as dataset:
          dataset.write(tile, indexes=1)
          dataset.write_colormap(1, colormap)
        memfile.seek(0)
        return memfile.read()
```

**Comment by vincentsarago** [comment]
@kriscarle I'm not sure to follow 100%
I made [this notebook](https://gist.github.com/vincentsarago/ecb5c15a1718c72b83aefedbcb2d7226) to try to explain my though. 

Basically your example does not imply any change in `rio_tiler` but it's more on the lambda handler side. What I think will be good is to add this in the documentation. 

>  plus I think this example can easily be adapted to support multiple bands.

I'm not sure to understand the concept of applying color palette to multiple bands. I'll be interested to see any use case for that.

**Comment by kriscarle** [comment]
@vincentsarago 

Yes, I ended up not needing to change rio-tiler, so it could just work as an example. Though it could still be a nice feature to automatically apply the color map from a VRT band if it is provided in the VRT. 

I'm not entirely sure what I meant by multiple bands either. I think I meant that you can create tiles for multiple bands and then combine them in some way. Maybe for calculating NVDI on the fly?
