### ISSUE TITLE
rio-tiler incompatible with rasterio 1.0b2

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/rio-tiler#44]
It looks like the rasterio release from today is breaking rio-tiler's functionality on my geotifs (which used to work before): https://github.com/mapbox/rasterio/releases/tag/1.0b2 Here is the error:

```
/tmp/rio/.env/lib/python3.5/site-packages/rio_tiler/utils.py:162: RasterioDeprecationWarning: dst_crs will
 be removed after 1.0, use crs
  with WarpedVRT(source, **vrt_params) as vrt:

Traceback (most recent call last):
  File "/tmp/rio/tiler.py", line 49, in <module>
    main()
  File "/tmp/rio/tiler.py", line 41, in main
    data, _ = tiler.tile(args.path, x, y, z)
  File "/tmp/rio/.env/lib/python3.5/site-packages/rio_tiler/main.py", line 75, in tile
    nodata=nodata, alpha=alpha)
  File "/tmp/rio/.env/lib/python3.5/site-packages/rio_tiler/utils.py", line 168, in tile_read
    indexes=indexes)
  File "rasterio/_warp.pyx", line 979, in rasterio._warp.WarpedVRTReaderBase.read
ValueError: WarpedVRT does not permit boundless reads
```

Workaround

```bash
pip install 'rasterio==1.0b1' 'rio-tiler==1.0a7'
```

Small self-contained reproducible program

https://gist.github.com/daniel-j-h/69a967d63d833f74a123e2540bd146b9

Geotifs are from OpenAerialMap, e.g.

https://oin-hotosm.s3.amazonaws.com/5ac7745591b5310010e0d49a/0/5ac7745591b5310010e0d49b.tif

Let me know if I'm doing something wrong here or if this is an issue with rasterio.

cc @dnomadb @sgillies @vincentsarago

**Comment by sgillies** [comment]
@daniel-j-h correct. I never intended Rasterio to be used like it was used in rio-tiler. Boundless reads from a warped VRT can't be supported by Rasterio in the future and I have revoked them intentionally.

**Comment by vincentsarago** [comment]
https://github.com/mapbox/rio-tiler/pull/45 fix it, just need to make the tests pass. 
I expected to have a new version of rio-tiler by EOD. 
I'll force the rasterio version to be `==1.0b2` to make sure we don't cause this kind of trouble again ;-)

**Comment by vincentsarago** [comment]
closed by https://github.com/mapbox/rio-tiler/pull/45 and https://github.com/mapbox/rio-tiler/pull/47
