### ISSUE TITLE
WarpedVRT does not permit boundless reads

### ISSUE THREAD

**Issue by talldave** [mapbox/rio-tiler#46]
"WarpedVRT does not permit boundless reads"
This is the error message I am getting with 1.0a7
If I change all boundless=True to boundless=False in utils.py, everything works again.

**Comment by vincentsarago** [comment]
Hi @talldave thanks for opening the issue. This is similar as https://github.com/mapbox/rio-tiler/issues/44 and I'm working on fixing everything on https://github.com/mapbox/rio-tiler/pull/45

**Comment by talldave** [comment]
That worked too.  I didn't have rasterio in my requirements.txt previously, just let rio-tiler pick the one it wanted.
