### ISSUE TITLE
Understanding the min-max metadata call

### ISSUE THREAD

**Issue by rowanwins** [mapbox/rio-tiler#55]
Hey @vincentsarago 

Hoping you can help me out by sharing a bit of knowledge (you're very good at it!)

I'm trying to tidy up a few loose ends on my [geotiff-server](https://github.com/rowanwins/geotiff-server) and one of the things that's given me a bit of grief is colour correction, building my own version of this repo has been a good crash course in imagery & colours! 

I _think_ I understand your approach but was hoping you could validate that I vaguely understand

### The process as I understand it
- Before making any calls to get tiles the web app sends a request to the server to get some generic information that'll be used for subsequent tiling
  - This involves sending the scene id to `metadata` endpoint

- During this metadata call the server [retrieves a 1024px x 1024px overview](https://github.com/mapbox/rio-tiler/blob/master/rio_tiler/utils.py#L43-L96) of each band for the entire geographic range of the scene 
  - the purpose of this is to get a feel for the range of values that might be across the scene (a rough way of generating a histogram) so that you can then colour balance the tiles accordingly
- You then get the percentiles for each band and sends them back to the web app (defaults to 2% and 98% to remove the extremes) 
  - You only use values that are greater than 0 because 0 are your `nodata` pixels

Am I vaguely on track with my understanding?

Thanks,
Rowan

**Comment by vincentsarago** [comment]
👋 @rowanwins you are 💯 right on everything 😄 

> You only use values that are greater than 0 because 0 are your nodata pixels

Landsat and Sentinel (as should be all optical imagery) have `0` as nodata.

> You then get the percentiles for each band and sends them back to the web app (defaults to 2% and 98% to remove the extremes)

Exactly then we do a linear recalling from `2%`= 0 to `98%`=255

**Comment by rowanwins** [comment]
Awesome thanks @vincentsarago - glad I haven't misinterpreted, now I just need to get it work :)

Doing this from almost scratch (just leveraging geotiff.js) has been a solid reminder of how valuable tools like `rasterio` & `gdal` are in this space!
